name: fiona_image_cache
description: This package helps your app to cache an image when get it from an URI.
version: 1.1.1
repository: https://github.com/iriber/fiona_image_cache

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
