name: fiona_image_cache
description: Fiona Image Cache package project.
version: 1.0.0
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  path: ^1.8.1
  cryptography: ^2.0.5
  get_it: ^7.6.0
  fiona_logger:
    path: "D:/trabajo/FlutterPackages/fiona_logger"
  path_provider: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
